version: 2

# Image to use
build:
  image: testing

sphinx:
  configuration: docs/conf.py

# Configuration
python:
  version: 3.12
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .
