https://github.com/jjjermiah/NBIA-toolkit/tree/main# Required
version: 2

# Image to use
build:
  image: testing

# Configuration
python:
  version: 3.12
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .
