version: 2

# Image to use
build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
sphinx:
  configuration: docs/conf.py
# Configuration
# need to install myst-nb, sphinx-autoapi, sphinx-rtd-theme,
# nbiatoolkit
python:
  install:
    - method: pip
      path: .