[project]
name = "nbia-toolkit"
version = "1.3.1"
description = "A python package to query the National Biomedical Imaging Archive (NBIA) database."
authors = [
  { name = "Jermiah Joseph" },
]
license = "MIT"
readme = "README.md"
requires-python = ">=3.10,<4"

dependencies = [
    "requests>=2.31.0,<3",
    "pydicom>=3.0",
    "tqdm>=4.66.1",
    "beautifulsoup4>=4.12.3",
    "cryptography>=42.0.2",
    "pandas>=2.2.0",
]

[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]


[tool.hatch.build]
directory = "dist"

[tool.hatch.build.targets.wheel]
packages = ["src/nbiatoolkit"]
include = ["pyproject.toml", "README.md", "src/**"]


[tool.semantic_release]
version_variables = [
    "src/nbiatoolkit/nbia.py:__version__",
]
version_toml = [
    "pyproject.toml:project.version",
]
dist_path = "dist/"
upload_to_release = true
upload_to_pypi = false
remove_dist = false
commit_message = "chore(sem-ver): {version}"
patch_without_tag = true

[tool.semantic_release.changelog]
changelog_file = "docs/project_info/CHANGELOG.md"
exclude_commit_types = ["docs", "style", "refactor", "test", "chore"]

[tool.semantic_release.branches.main]
match = "(main|master|development)"

[tool.semantic_release.commit_parser_options]
allowed_tags = [
    "build",
    "chore",
    "ci",
    "feat",
    "fix",
    "perf",
    "style",
    "refactor",
    "test",
    "docs"
]
minor_tags = [
    "feat"]
patch_tags = [
    "build",
    "ci",
    "perf",
    "refactor",
    "style",
    "test",
    "fix",
    "docs"
]